# `root.yaml` sets up the buildroot for `osbuild`.
name: root
source-epoch: 1659397331
stages:
  - otk.external.osbuild.depsolve-dnf4:
      architecture: ${architecture}
      module_platform_id: f${version}
      docs: ${packages.root.docs}
      weak: ${packages.root.weak}
      repositories: ${packages.repositories}
      gpgkeys: ${packages.keys}
      packages:
        include:
          otk.op.seq.merge:
            values:
              - ${packages.root.packages.include}
              - ${packages.todo.packages.include}
        exclude:
          otk.op.seq.merge:
            values:
              - ${packages.root.packages.exclude}
              - ${packages.todo.packages.exclude}
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
      labels:
        /usr/bin/cp: system_u:object_r:install_exec_t:s0
        /usr/bin/tar: system_u:object_r:install_exec_t:s0
