otk.define:
  filesystem:
    otk.external.osbuild-gen-partition-table:
      modifications:
        ${filesystem.modifications}
      properties:
        type: dos
        bios: true
        default_size: "10 GiB"
        uuid: "0x14fc63d2"
        create:
          bios_boot_partition: false
          esp_partition: false
      partitions:
        - name: boot
          mountpoint: /boot
          label: boot
          size: "1 GiB"
          type: "xfs"
          fs_mntops: defaults
        - mountpoint: /
          type: "xfs"
          size: "2 GiB"
          fs_mntops: defaults
          bootable: true
  # XXX: it would be nicer if the "fs_options" could be part of their
  # stages directly without this indirection.
  fs_options:
    otk.external.osbuild-make-partition-mounts-devices:
      ${filesystem}
