name: tree
build: name:root
stages:
  - otk.external.osbuild_depsolve_dnf4:
      architecture: ${architecture}
      releasever: "40"
      module_platform_id: f${version}
      repositories: ${packages.repositories}
      gpgkeys: ${packages.keys}
      docs: ${packages.tree.docs}
      weak: ${packages.tree.weak}
      packages: ${packages.tree.packages}
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid: ${filesystem.root.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
  - type: org.osbuild.fstab
    options:
      filesystems:
        - ${filesystem.boot}
        - ${filesystem.boot-efi}
        - ${filesystem.root}
  - type: org.osbuild.grub2
    options:
      root_fs_uuid: ${filesystem.root.uuid}
      boot_fs_uuid: ${filesystem.boot.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
      legacy: i386-pc
      uefi:
        vendor: fedora
        unified: true
      # TODO: expose this somehow from the depsolve
      saved_entry: "ffffffffffffffffffffffffffffffff-${version}"
      write_cmdline: false
      config:
        default: saved
  - otk.include: osbuild/stage/fix-bls.yaml
  - otk.include: osbuild/stage/locale.yaml
  - otk.include: osbuild/stage/hostname.yaml
  - otk.include: osbuild/stage/timezone.yaml
  - otk.include: osbuild/stage/selinux.yaml
