name: tree
build: name:root
stages:
  - otk.external.osbuild.depsolve-dnf4:
      architecture: ${architecture}
      module_platform_id: f${version}
      repositories: ${packages.repositories}
      gpgkeys: ${packages.keys}
      docs: ${packages.tree.docs}
      weak: ${packages.tree.weak}
      packages: ${packages.tree.packages}
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid: ${filesystem.root.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
  - type: org.osbuild.fix-bls
    options:
      prefix: ''
  - type: org.osbuild.locale
    options:
      language:
        otk.customization.locale:
          scope: tree
          default:
            language: en_US
          if-set:
            language: en_US
  - type: org.osbuild.hostname
    options:
      language:
        otk.customization.hostname:
          scope: tree
          default:
            hostname: localhost.localdomain
          if-set:
            language: localhost.localdomain
  - type: org.osbuild.timezone
    options:
      language:
        otk.customization.language:
          scope: tree
          default:
            zone: UTC
          if-set:
            zone: UTC
  - type: org.osbuild.fstab
    options:
      filesystems:
        - ${filesystem.boot}
        - ${filesystem.boot-efi}
        - ${filesystem.root}
  - type: org.osbuild.grub2
    options:
      root_fs_uuid: ${filesystem.root.uuid}
      boot_fs_uuid: ${filesystem.boot.uuid}
      kernel_opts: ro no_timer_check console=ttyS0,115200n8 biosdevname=0 net.ifnames=0
      legacy: i386-pc
      uefi:
        vendor: fedora
        unified: true
      # TODO: expose this somehow from the depsolve
      saved_entry: "ffffffffffffffffffffffffffffffff-${version}"
      write_cmdline: false
      config:
        default: saved
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
