name: root
source-epoch: 1659397331
stages:
  - otk.external.osbuild.depsolve-dnf4:
    architecture: $architecture
    module_platform_id: f$version
    repositories: $repositories
    gpgkeys: $gpgkeys
    exclude:
      docs: true
    packages: $packages.default.root
  - name: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
      labels:
        /usr/bin/cp: system_u:object_r:install_exec_t:s0
        /usr/bin/tar: system_u:object_r:install_exec_t:s0
