name: build
# source-epoch will support reproducible builds:
# https://reproducible-builds.org/docs/source-date-epoch/
source-epoch: ${source_epoch}
runner: "org.osbuild.centos${version}"
stages:
  otk.op.join:
    values:
      - ${packages.build.stages}
      - - type: org.osbuild.selinux
          options:
            file_contexts: etc/selinux/targeted/contexts/files/file_contexts
            labels:
              /usr/bin/cp: system_u:object_r:install_exec_t:s0
              /usr/bin/tar: system_u:object_r:install_exec_t:s0
