name: image
build: "name:build"

stages:
  - otk.external.osbuild_partition_table.gen_truncate_stage:
    from: filesystems
  - otk.external.osbuild_partition_table.gen_sfdisk_stage:
    from: filesystems
  - otk.external.osbuild_partition_table.gen_mkfs_stages:
    from: filesystems
  - type: org.osbuild.copy
    options:
      paths:
        from: input://root-tree/
        to: mount://-/
    devices:
      otk.external.osbuild.partition_table.gen_devices:
      from: filesystems
    mounts:
      otk.external.osbuild.partition_table.gen_mounts:
      from: filesystems
  # TODO drop this stage conditionally on legacy boot support (or not) [is this our use-case for conditionals?]
  - type: org.osbuild.grub2.inst
    options:
      filename: image.raw
      platform: i386-pc
      location: 2048
      core:
        type: mkimage
        partlabel: gpt
        filesystem: xfs
      prefix:
        type: partition
        partlabel: gpt
        number: 2
        path: /grub2
