name: os
build: "name:build"

stages:
  # Install RPMs
  - otk.external.osbuild_depsolve_dnf4:
    architecture: ${architecture}
    releasever: ${version}
    module_platform_id: platform:el${version}
    docs: ${packages.os.docs}
    weak: ${packages.os.weak}
    repositories: ${packages.repositories}
    gpgkeys: ${packages.keys}
    packages: ${packages.os.packages}

  # Disk bits
  - otk.external.osbuild.partition_table.gen_fstab_stage:
    source: ${filesystem}

  # Boot bits
  - otk.include: fragment/kernel-cmdline.yaml
  - otk.include: fragment/dracut.yaml
  - otk.include: fragment/fix-bls.yaml
  - otk.include: fragment/grub2.yaml

  # General bits, could probably be split out further
  - otk.include: fragment/locale.yaml
  - otk.include: fragment/keymap.yaml
  - otk.include: fragment/timezone.yaml
  - otk.include: fragment/chrony.yaml
  - otk.include: fragment/sysconfig.yaml
  - otk.include: fragment/systemd-logind.yaml
  - otk.include: fragment/cloud-init.yaml
  - otk.include: fragment/modprobe.yaml
  - otk.include: fragment/authselect.yaml
  - otk.include: fragment/sshd.yaml
  - otk.include: fragment/systemd-unit.yaml
  - otk.include: fragment/systemd.yaml

  - otk.include: fragment/users.yaml
  - otk.include: fragment/oscap.yaml

  # Always
  - otk.include: fragment/selinux.yaml
