name: root
build: "name:build"

stages:
  otk.op.join:
    values:
      - ${packages.root.stages}

      # Boot bits
      - otk.include: ../fragment/kernel-cmdline.yaml
      - otk.include: ../fragment/dracut.yaml
      - otk.include: ../fragment/fix-bls.yaml
      - otk.include: ../fragment/grub2.yaml

      - - otk.external.otk-make-fstab-stage: ${filesystem}

      # General bits, could probably be split out further
      - otk.include: ../fragment/locale.yaml
      - otk.include: ../fragment/keymap.yaml
      # - otk.include: ../fragment/chrony.yaml
      - otk.include: ../fragment/sysconfig.yaml
      - otk.include: ../fragment/systemd-logind.yaml
      # - otk.include: ../fragment/cloud-init.yaml
      - otk.include: ../fragment/modprobe.yaml
      - otk.include: ../fragment/authselect.yaml
      - otk.include: ../fragment/sshd.yaml
      - otk.include: ../fragment/systemd-unit.yaml
      - otk.include: ../fragment/systemd.yaml

      # Always
      - otk.include: ../fragment/selinux.yaml
