#!/usr/bin/python3
# pylint: disable=invalid-name

import json
import os
import pathlib
import subprocess
import sys
import tempfile

import yaml


# see https://github.com/yaml/pyyaml/issues/234#issuecomment-765894586
class Dumper(yaml.Dumper):  # pylint: disable=too-many-ancestors
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow=flow, indentless=False)


def generate_reference_image(images_base_dir: str, distro_name: str, distro_ver: str, arch: str, img_type: str) -> None:
    # pylint: disable=consider-using-with
    empty_config = tempfile.NamedTemporaryFile()
    empty_config.write(b'{"name": "empty"}')
    empty_config.flush()

    # ideally we would just generate all manifests on the fly but today
    # that requires a git checkout of "images". with something like
    # https://github.com/osbuild/images/pull/902 we could automate this
    # here and just call the remote binary via "go run"
    env = os.environ.copy()
    env["OSBUILD_TESTING_RNG_SEED"] = "0"
    distro = f"{distro_name}-{distro_ver}"
    manifest_path = pathlib.Path.cwd() / distro_name / distro_ver / arch / img_type
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.check_call([
        "cmd/gen-manifests/gen-manifests",
        "-output", manifest_path,
        "-packages=False", "-commits=False",
        "-containers=False", "-metadata=False",
        "-distros", distro,
        "-arches", arch,
        "-types", img_type,
        "-config", empty_config.name,
    ], cwd=images_base_dir, env=env)
    generated = list(manifest_path.glob("*.json"))
    if len(generated) != 1:
        raise ValueError(f"unexpected number of generated manifests: {generated}")
    with open(generated[0], encoding="utf8") as fp:
        manifest_str = fp.read()

    # XXX: this is hacky, the OSBUILD_TESTING_RNG_SEED is set for both
    # "gen-manifests" and "otk-gen-partition-tables" but the partition
    # table code is called slightly differently which means that the UUIDs
    # get out of sync. We need this (f)ugly mapping here to fix that.
    #
    # "gen-manifests" root UUID -> "otk-gen-partition-table" UUID (qcow2)
    manifest_str = manifest_str.replace("dde1466f-f75b-4f05-bcf6-8386564c6f79", "9851898e-0b30-437d-8fad-51ec16c3697f")
    # ami
    manifest_str = manifest_str.replace("1d5b4d74-fd75-4ba1-a6e1-f1737dd4cdd1", "9851898e-0b30-437d-8fad-51ec16c3697f")
    # fedora 40/minimal-raw
    manifest_str = manifest_str.replace("bf59b5df-279f-44e3-9320-77de18d2c4f7", "9851898e-0b30-437d-8fad-51ec16c3697f")
    # fedora40/minimal-raw/aarch64
    manifest_str = manifest_str.replace("b1a2302c-2db6-49d4-bd83-ffcfaf27ba37", "9851898e-0b30-437d-8fad-51ec16c3697f")
    # "gen-manifests" boot UUID -> "otk-gen-partition-table" UUID (qcow2)
    manifest_str = manifest_str.replace("e4520b54-3a3f-4ed3-b8a6-e326beec8e93", "dbd21911-1c4e-4107-8a9f-14fe6e751358")
    # ami
    manifest_str = manifest_str.replace("44019259-d936-49a3-a807-063467c4551a", "dbd21911-1c4e-4107-8a9f-14fe6e751358")
    # fedora 40/minimal-raw
    manifest_str = manifest_str.replace("183791e1-f506-4579-973c-1af91a080f19", "dbd21911-1c4e-4107-8a9f-14fe6e751358")
    # fedora40/minimal-raw/aarch64
    manifest_str = manifest_str.replace("95f06a9d-54e3-4b4e-a9a4-18fccbe0b448", "dbd21911-1c4e-4107-8a9f-14fe6e751358")
    

    # now convert to json
    manifest = json.loads(manifest_str)

    yaml_path = generated[0].with_suffix(".yaml")
    with yaml_path.open("w", encoding="utf8") as fp:
        yaml.dump(manifest, fp, Dumper=Dumper, sort_keys=False)
    print(f"image generated in {yaml_path}")


def run():
    # TODO: add argparse
    if len(sys.argv) < 5:
        # TODO: remove images-git-checkout parameter and use something
        # like "go run github.com/osbuild/images/cmd/build@latest" but
        # this needs something like https://github.com/osbuild/images/pull/902
        print("need <image-git-checkout> <distoname> <distrover> <arch> <img_type> argument", file=sys.stderr)
        sys.exit(1)
    generate_reference_image(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])


if __name__ == "__main__":
    run()
