name: image
build: name:build
stages:
  otk.op.join:
    values:
      - otk.external.otk-make-partition-stages:
          ${filesystem}
      - - type: org.osbuild.copy
          inputs:
            root-tree:
              type: org.osbuild.tree
              origin: org.osbuild.pipeline
              references:
                - name:os
          options:
            paths:
              - from: input://root-tree/
                to: mount://-/
          devices:
            ${fs_options.devices}
          mounts:
            ${fs_options.mounts}
        - otk.external.otk-make-grub2-inst-stage:
            platform: powerpc-ieee1275
            filesystem: ${filesystem}
