name: Build & Deploy

"on":
  release:
  push:

jobs:
  build-base:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker image metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/osbuild/otk
          tags: |
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest
            type=sha,format=long,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Containerfile
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          cache-from: type=registry,ref=ghcr.io/osbuild/otk:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
